spring:
  cloud:
    config:
      server:
        git:
          uri: http://localhost:3000/olan/config-files.git
          search-paths: '{application}'
          default-label: master
          force-pull: true
          delete-untracked-branches: true
          ignore-local-ssh-settings: true
          username: olan
          password: 'Admin1234:'
